version: '3.7'

services:
  app:
    image: node:20-alpine

    command: sh -c "npm install && npm run dev"

    ports:
      - 8000:8000

    working_dir: /app

    volumes:
      - ./:/app

    environment:
      REACT_APP_HOST_DEV: $REACT_APP_HOST_DEV
      REACT_APP_HOST_IMAGE_DEV: $REACT_APP_HOST_IMAGE_DEV
    
    restart: always