export const START_FETCHING_ORGANIZERS =
  'redux/organizers/START_FETCHING_ORGANIZERS'
export const SUCCESS_FETCHING_ORGANIZERS =
  'redux/organizers/SUCCESS_FETCHING_ORGANIZERS'
export const ERROR_FETCHING_ORGANIZERS =
  'redux/organizers/ERROR_FETCHING_ORGANIZERS'

export const SUCCESS_ADD_ORGANIZER = 'redux/organizers/SUCCESS_ADD_ORGANIZER'
export const SUCCESS_ADD_ADMIN = 'redux/organizers/SUCCESS_ADD_ADMIN'
