export const START_FETCHING_PAYMENTS = 'redux/payments/START_FETCHING_PAYMENTS'
export const SUCCESS_FETCHING_PAYMENTS =
  'redux/payments/SUCCESS_FETCHING_PAYMENTS'
export const ERROR_FETCHING_PAYMENTS = 'redux/payments/ERROR_FETCHING_PAYMENTS'
export const SUCCESS_ADD_PAYMENT = 'redux/payments/SUCCESS_ADD_PAYMENT'
export const SUCCESS_EDIT_PAYMENT = 'redux/payments/SUCCESS_EDIT_PAYMENT'
export const SUCCESS_DELETE_PAYMENT = 'redux/payments/SUCCESS_DELETE_PAYMENT'
